const dataSource =
  [
    {
      category: '',
      id: 0,
      name: 'hello',
      value: '',
      label: '11132',
      path: '/vue2.x-official-demos/01_hello.html'
    },
    {
      category: '',
      id: 1,
      name: 'v-bind',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/02_v-bind.html',
    },
    {
      category: '',
      id: 2,
      name: 'v-if',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/03_v-if.html',
    },
    {
      category: '',
      id: 3,
      name: 'v-for',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/04_v-for.html',
    },
    {
      category: '',
      id: 4,
      name: 'v-on',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/05_v-on.html',
    },
    {
      category: '',
      id: 5,
      name: 'v-model',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/06_v-model.html',
    },
    {
      category: '',
      id: 6,
      name: '数据与方法',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/07_数据与方法.html',
    },
    {
      category: '',
      id: 7,
      name: 'freeze',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/08_freeze.html',
    },
    {
      category: '',
      id: 8,
      name: 'Vue实例property',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/09_Vue实例property.html',
    },
    {
      category: '',
      id: 9,
      name: '生命周期',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/10_生命周期.html',
    },
    {
      category: '',
      id: 10,
      name: 'v-once',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/11_v-once.html',
    },
    {
      category: '',
      id: 11,
      name: 'v-html',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/12_v-html.html',
    },
    {
      category: '',
      id: 12,
      name: '指令介绍',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/13_指令介绍.html',
    },
    {
      category: '',
      id: 13,
      name: 'Class_Style',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/14_Class_Style.html',
    },
    {
      category: '',
      id: 14,
      name: 'v-else',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/15_v-else.html',
    },
    {
      category: '',
      id: 15,
      name: 'v-show',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/16_v-show.html',
    },
    {
      category: '',
      id: 16,
      name: 'v-for',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/17_v-for.html',
    },
    {
      category: '',
      id: 17,
      name: 'v-on进阶',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/18_v-on进阶.html',
    },
    {
      category: '',
      id: 18,
      name: '表单输入绑定',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/19_表单输入绑定.html',
    },
    {
      category: '',
      id: 19,
      name: '值绑定',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/20_值绑定.html',
    },
    {
      category: '',
      id: 20,
      name: '修饰符',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/21_修饰符.html',
    },
    {
      category: '',
      id: 21,
      name: '组件基础',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/22_组件基础.html',
    },
    {
      category: '',
      id: 22,
      name: '组件注册',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/23_组件注册.html',
    },
    {
      category: '',
      id: 23,
      name: 'computed_计算属性',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/24_computed_计算属性.html',
    },
    {
      category: '',
      id: 24,
      name: 'watch_侦听属性',
      value: '',
      label: '',
      path: '/vue2.x-official-demos/25_watch_侦听属性.html',
    },
  ]

export default dataSource
