import Vue from 'vue'
// 按需导入Vant组件
import { Popup, Cell, CellGroup, Button, Switch, Tabbar, TabbarItem, Icon, NavBar, Toast, Dialog, Loading, Notify, ActionSheet, Search, Swipe, SwipeItem, Lazyload, Grid, GridItem, Divider, Image as VanImage, ImagePreview } from 'vant'
// 注册
Vue.use(Button)
Vue.use(Switch)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(Icon)
Vue.use(NavBar)
Vue.use(Toast)
Vue.use(Dialog)
Vue.use(Loading)
Vue.use(Notify)
Vue.use(ActionSheet)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Lazyload)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Popup)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Divider)
Vue.use(VanImage)
Vue.use(ImagePreview)