const dataSource =
  [
    {
      category: '',
      id: 0,
      name: 'helloworld',
      value: '',
      label: '11132',
      path: '/vue2-4hours-demos/01_helloworld.html'
    },
    {
      category: '',
      id: 1,
      name: 'el',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/02_el.html',
    },
    {
      category: '',
      id: 2,
      name: 'data',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/03_data.html',
    },
    {
      category: '',
      id: 3,
      name: 'v-text',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/04_v-text.html',
    },
    {
      category: '',
      id: 4,
      name: 'v-html',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/05_v-html.html',
    },
    {
      category: '',
      id: 5,
      name: 'v-on',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/06_v-on.html',
    },
    {
      category: '',
      id: 6,
      name: '计数器',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/07_计数器.html',
    },
    {
      category: '',
      id: 7,
      name: 'v-show',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/08_v-show.html',
    },
    {
      category: '',
      id: 8,
      name: 'v-if',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/09_v-if.html',
    },
    {
      category: '',
      id: 9,
      name: 'v-bind',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/10_v-bind.html',
    },
    {
      category: '',
      id: 10,
      name: '图片切换',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/11_图片切换/11_图片切换.html',
    },
    {
      category: '',
      id: 11,
      name: 'v-for',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/12_v-for.html',
    },
    {
      category: '',
      id: 12,
      name: 'v-on补充',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/13_v-on补充.html',
    },
    {
      category: '',
      id: 13,
      name: 'Class_Style',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/14_Class_Style.html',
    },
    {
      category: '',
      id: 14,
      name: '记事本',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/15_记事本/15_记事本.html',
    },
    {
      category: '',
      id: 15,
      name: 'axios基本使用',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/16_axios基本使用.html',
    },
    {
      category: '',
      id: 16,
      name: 'axios+vue',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/17_axios+vue.html',
    },
    {
      category: '',
      id: 17,
      name: '天知道',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/18_天知道/index.html',
    },
    {
      category: '',
      id: 18,
      name: '音乐播放器',
      value: '',
      label: '',
      path: '/vue2-4hours-demos/19_音乐播放器/index.html',
    },
  ]

export default dataSource
